# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
#
# - task: CopyFiles@2
#   inputs:
#     Contents: |
#       parameters.json
#       template.json
#     TargetFolder: $(Build.ArtifactStagingDirectory)/Template
#
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: Website
#     targetPath: '$(Build.ArtifactStagingDirectory)/Website'
#
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: Template
#     targetPath: '$(Build.ArtifactStagingDirectory)/Template'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    workingDirectory: Words.Core
    command: publish
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
