name: Build

on:
  push:
    branches: [master]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Build
      run: dotnet build --configuration Release Words.Core.sln

    - name: Test
      run: dotnet test --no-restore --configuration Release Words.Core.sln

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Build
      run: msbuild -t:Build -p:Configuration=Release Words.sln
